[package]
name = "git-build-version"
version = "0.1.0"
authors = ["Ceri Storey <packages@ceri.storey.name>"]

[dependencies]
git2 = { version = "0.3.3", default-features = false, features = [] }
quick-error = "0.1.4"
